app:
  port: {{.Port}}
  host: "0.0.0.0"

routing:
  appDir: "./app"
  publicDir: "./public"

ebpf:
  enabled: false

rendering:
  mode: "ssr"

logging:
  level: "info"
  format: "text"

# plugins:
#   enabled: []
#   dir: "./plugins"
#   config: {}

